# Generated by Django 2.0.6 on 2020-04-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leoparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='docdelta',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='leoparser.Rule'),
        ),
        migrations.AddField(
            model_name='parser',
            name='rule_set',
            field=models.ManyToManyField(related_name='parsers', to='leoparser.Rule', verbose_name='rule'),
        ),
    ]
